// This header is normally generated by CMake during cmark's build process.
// We provide a minimal version for Zig build compatibility.
// See: https://github.com/commonmark/cmark

#ifndef CMARK_EXPORT_H
#define CMARK_EXPORT_H

// For static linking, CMARK_EXPORT is empty
#define CMARK_EXPORT

#endif
